version: '3.9'

services:
  backend:
    container_name: store-backend
    build:
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge